DROP TABLE IF EXISTS product, list_of_products CASCADE;
CREATE TABLE list_of_products (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name varchar(100) NOT NULL
);
CREATE TABLE product (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_of_product_id int REFERENCES list_of_products(id),
    name varchar(100) NOT NULL UNIQUE,
    weight varchar(50) NOT NULL,
    description varchar(200) NOT NULL
);

